source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'chatDemo' do
  pod 'Masonry'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'GoogleSignIn'
  pod 'MBProgressHUD'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Auth'
  pod 'JSQMessagesViewController'
  pod 'Firebase/Storage'
  pod 'AFNetworking'
  pod 'MWPhotoBrowser'
  pod 'AKLocationManager'
end
